### ISSUE TITLE
yum update exits with gandi-hosting-vm2 not signed error

### ISSUE THREAD

**Issue by AJDulk** [Gandi/gandi-vm-config#10]
I have just created a new CentOS 7 server. First step for new install is to update the system using yum. When I do this I get an error from yum that gandi-hosting-vm2 is not signed.

I am able to update then using the --nogpgcheck flag on yum, this of course destroys the security offered by requiring signed commits.

**Comment by aegiap** [comment]
Hello @AJDulk can you try to install the gandi-hosting-vm2 package from Gandi repository at https://mirrors.gandi.net/centos ? Our repository should be correctly signed now.

**Comment by David-5-1** [comment]
I am not seeing the issue now, so I guess it is fixed -:)
