### ISSUE TITLE
Secondary network interface not provisioned with IPV4 address

### ISSUE THREAD

**Issue by ctrlaltca** [Gandi/gandi-vm-config#6]
Hi, today i `yum update`d my centos 7 vps running at LU-BI1.
The `gandi-hosting-vm2-2.18-1.noarch` and a few other packages including the kernel were updated, so i rebooted the vps after the update.
The vps has 2 network interfaces attached; after the reboot, the second one (eth1) did not get its IPV4 address assigned automatically as before.

If i try to manually bring up the interface using `manage_iface.sh` i see this error:
```sh
[root@centos7 ~]# INTERFACE=eth1 ACTION=add /etc/gandi/manage_iface.sh
Traceback (most recent call last):
  File "/usr/share/gandi/get_json.py", line 65, in <module>
    sys.exit(need_dhcp_config(configfile, ifaceid))
  File "/usr/share/gandi/get_json.py", line 25, in need_dhcp_config
    vifs = [vif for vif in content['vif'] if vif['vif_number'] ==
int(ifaceid)]
KeyError: 'vif'
combined unmodified, ignoring
no channel parameters changed, aborting
current values: tx 0 rx 0 other 0 combined 2
```
Looks like the involved code has been introduced in a recent change
https://github.com/Gandi/gandi-vm-config/commit/eed014105d1b1cbcc8f7df8876a3301b724b5145#diff-2afe27a1b51c7833f9d28dfdb4205602R71

The script is trying to load some values from a json file that is empty:
 ```sh
[root@centos7 ~]# cat /gandi/config
{}
```

As far as i understand this, the manage_iface.sh errors out before it runs dhclient
on the interface, so the interface doesn't get its IPV4 address assigned.
If i manually run `ip addr add xx.xx.xx.xx dev eth1` with the correct ip the interface starts to work normally.

**Comment by ctrlaltca** [comment]
Today the package received an update: `gandi-hosting-vm2.noarch 0:2.21-1`.

**Comment by ctrlaltca** [comment]
Today kernel got updated, still same problem.

**Comment by aegiap** [comment]
@ctrlaltca can you try with the latest release 2.27 available ?

**Comment by ctrlaltca** [comment]
I've just updated to `gandi-hosting-vm2-2.27-1.noarch.rpm`.
This night (CET) i'll reboot the server and report back.
Thank you!

**Comment by citadev** [comment]
Hi, Same problem here with gandi-hosting-vm2 2.27 on a debian 9 server.
After reboot, no ipv4 address on eth1 (private network).

But `INTERFACE=eth1 ACTION=add /etc/gandi/manage_iface.sh` bring up the interface and default route correctly.

Any idea ?

**Comment by ctrlaltca** [comment]
I confirm the results of my last report:
```
Jul 20 07:26:53 centos7 gandi[1262]: Setup of eth1
...
Jul 20 07:26:53 centos7 systemd[1]: Started Gandi-bootstrap early setup the system.
Jul 20 07:26:53 centos7 systemd[1]: Starting Gandi-config configures network, hostname and else on your VM at boot...
...
Jul 20 07:26:57 centos7 network[1282]: Bringing up interface eth0:  [  OK  ]
Jul 20 07:26:58 centos7 network[1282]: Bringing up interface eth1:
Jul 20 07:26:58 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 5 (xid=0x1a2c2a1)
Jul 20 07:27:03 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 8 (xid=0x1a2c2a1)
Jul 20 07:27:11 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 9 (xid=0x1a2c2a1)
Jul 20 07:27:20 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 11 (xid=0x1a2c2a1)
Jul 20 07:27:31 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 21 (xid=0x1a2c2a1)
Jul 20 07:27:52 centos7 dhclient[2036]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 7 (xid=0x1a2c2a1)
...
Jul 20 07:27:59 centos7 dhclient[2036]: No DHCPOFFERS received.
Jul 20 07:27:59 centos7 network[1282]: Determining IP information for eth1... failed.
Jul 20 07:27:59 centos7 network[1282]: [FAILED]
Jul 20 07:27:59 centos7 systemd[1]: network.service: control process exited, code=exited status=1
Jul 20 07:27:59 centos7 systemd[1]: Failed to start LSB: Bring up/down networking.
Jul 20 07:27:59 centos7 systemd[1]: Unit network.service entered failed state.
Jul 20 07:27:59 centos7 systemd[1]: network.service failed.

```

**Comment by ctrlaltca** [comment]
Today i updated the distro to Centos 7.4, still not getting the ip address on the second interface.
gandi-hosting-vm2 package version is 2.29-1.

**Comment by stephen-smith** [comment]
Continuing to have this problem with Debian 9.  I don't get my IPv4 addresses on a normal boot, have to go in through the console to add them each boot.  Very painful.

**Comment by ctrlaltca** [comment]
Rebooted the server a few minutes ago, it picked up both interfaces's ip correctly form dhcp. 😕

**Comment by ctrlaltca** [comment]
This looks like it's working in the few last reboots i did, thus i'm closing the issue.
