### ISSUE TITLE
Using autofs for automounting disk does not honor `CONFIG_DISK_ROOT`

### ISSUE THREAD

**Issue by b3** [Gandi/gandi-vm-config#7]
Recommandations given in https://wiki.gandi.net/en/iaas/references/disk/mount are bad since it does not honor `CONFIG_DISK_ROOT` variable since `/srv` is hardcoded in autofs config files.

I think that this is due to commit e14174315d52cf31c3218349e74f213ec6b63605

**Comment by David-5-1** [comment]
The new documentation no longer gives detail on `CONFIG_DISK_ROOT` so I guess no more action will be taken on this.
